// resources/js/Components/Sidebar/SidebarConfig.js
import {
    Home,
    MessageSquare,
    CheckSquare,
    Users,
    Settings,
    Calendar,
    Folder,
    Briefcase,
    Clock,
    BarChart,
    File,
    Shield,
    Server,
    Plug,
    Activity,
    Bell,
    Search,
    Plus,
    Share2,
    Lightbulb,
    Kanban // Add Kanban icon
} from 'lucide-react';

export const sidebarConfig = {
    super_admin: [
        { id: 'dashboard', name: 'Dashboard', icon: 'Home', href: '/dashboard' },
        { id: 'projects', name: 'Projects', icon: 'Folder', href: '/projects' },
        { id: 'tasks', name: 'Tasks', icon: 'CheckSquare', href: '/tasks' },
        { id: 'teams', name: 'Teams & Members', icon: 'Users', href: '/teams' },
        { id: 'clients', name: 'Clients', icon: 'Briefcase', href: '/clients' },
        { id: 'time-tracking', name: 'Time Tracking', icon: 'Clock', href: '/time-tracking' },
        { id: 'reports', name: 'Reports & Analytics', icon: 'BarChart', href: '/reports' },
        { id: 'files', name: 'Files', icon: 'File', href: '/files' },
        { id: 'calendar', name: 'Calendar', icon: 'Calendar', href: '/calendar' },
        { id: 'discussions', name: 'Discussions', icon: 'MessageSquare', href: '/discussions' },
        { id: 'settings', name: 'Settings', icon: 'Settings', href: '/settings' },
        { id: 'roles', name: 'User Roles & Permissions', icon: 'Shield', href: '/roles' },
        { id: 'system-settings', name: 'System Settings', icon: 'Server', href: '/system-settings' },
        { id: 'integrations', name: 'Integrations', icon: 'Plug', href: '/integrations' },
        { id: 'activity-logs', name: 'Activity Logs', icon: 'Activity', href: '/activity-logs' },
    ],
    manager: [
        { id: 'dashboard', name: 'Dashboard', icon: 'Home', href: '/dashboard' },
        { id: 'projects', name: 'Projects', icon: 'Folder', href: '/projects' },
        { id: 'tasks', name: 'Task Board', icon: 'Kanban', href: '/tasks' }, // Changed to Kanban icon
        { id: 'team-members', name: 'Team Members', icon: 'Users', href: '/team-members' },
        { id: 'discussions', name: 'Discussions', icon: 'MessageSquare', href: '/discussions' },
        { id: 'files', name: 'Files', icon: 'File', href: '/files' },
        { id: 'calendar', name: 'Calendar', icon: 'Calendar', href: '/calendar' },
        { id: 'time-tracking', name: 'Time Tracking', icon: 'Clock', href: '/time-tracking' },
        { id: 'reports', name: 'Reports', icon: 'BarChart', href: '/reports' },
    ],
    team_member: [
        { id: 'dashboard', name: 'Dashboard', icon: 'Home', href: '/dashboard' },
        { id: 'my-tasks', name: 'My Tasks', icon: 'CheckSquare', href: '/my-tasks' },
        { id: 'projects', name: 'Projects', icon: 'Folder', href: '/projects' },
        { id: 'discussions', name: 'Discussions', icon: 'MessageSquare', href: '/discussions' },
        { id: 'files', name: 'Files', icon: 'File', href: '/files' },
        { id: 'calendar', name: 'Calendar', icon: 'Calendar', href: '/calendar' },
        { id: 'time-log', name: 'My Time', icon: 'Clock', href: '/my-time' },
    ],
    client: [
        { id: 'dashboard', name: 'Dashboard', icon: 'Home', href: '/dashboard' },
        { id: 'projects', name: 'Projects', icon: 'Folder', href: '/projects' },
        { id: 'discussions', name: 'Discussions', icon: 'MessageSquare', href: '/discussions' },
        { id: 'files', name: 'Files', icon: 'File', href: '/files' },
        { id: 'calendar', name: 'Calendar', icon: 'Calendar', href: '/calendar' },
    ]
};

export const iconMap = {
    Home,
    MessageSquare,
    CheckSquare,
    Users,
    Settings,
    Calendar,
    Folder,
    Briefcase,
    Clock,
    BarChart,
    File,
    Shield,
    Server,
    Plug,
    Activity,
    Bell,
    Search,
    Plus,
    Share2,
    Lightbulb,
    Kanban: CheckSquare // Use CheckSquare as Kanban icon for now
};